[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
dotnet build (Join-Path $root 'BootLens.sln') -c Release
dotnet test (Join-Path $root 'BootLens.sln') -c Release --no-build --no-restore
& (Join-Path $PSScriptRoot 'validate-localization.ps1')
$forbidden = rg -n -i 'generated by (assistant|model|system)|created with (assistant|model|system)' -g '!bin/**' -g '!obj/**' -g '!artifacts/**' -g '!scripts/release-validation.ps1' $root
if ($LASTEXITCODE -eq 0) { throw 'Forbidden production references were found.' }
$secretMatches = rg -n -i 'api[_-]?key\s*=|password\s*=|secret\s*=|BEGIN (RSA|OPENSSH|PRIVATE)' -g '!bin/**' -g '!obj/**' -g '!artifacts/**' $root
if ($LASTEXITCODE -eq 0) { throw 'Potential secret material was found.' }
Write-Output 'Release validation completed: build, tests, localization, forbidden-reference scan and secret scan passed.'
